/** Reference data (city/country names in Armenian, airlines, visa rules) generated by `trichq reference`. */

type CityRow = [hy: string, en: string, cc: string | null, lat: number | null, lon: number | null];

interface Places {
  cities: Record<string, CityRow>;
  countries: Record<string, [string, string]>;
  airlines: Record<string, string>;
  visa: Record<string, string>;
}

let places: Places = { cities: {}, countries: {}, airlines: {}, visa: {} };

export async function loadPlaces(): Promise<void> {
  try {
    const resp = await fetch("/ref/places.json", { cache: "force-cache" });
    if (resp.ok) places = (await resp.json()) as Places;
  } catch {
    /* names fall back to IATA codes */
  }
}

export const cityName = (code: string): string => places.cities[code]?.[0] ?? code;
export const countryCode = (code: string): string | null => places.cities[code]?.[2] ?? null;
export const countryName = (code: string): string => {
  const cc = countryCode(code);
  return (cc && places.countries[cc]?.[0]) || "";
};
export const coords = (code: string): [number, number] | null => {
  const c = places.cities[code];
  return c && c[3] !== null && c[4] !== null ? [c[3], c[4]] : null;
};
export const airlineName = (code: string | null): string => (code ? places.airlines[code] ?? code : "");

export type VisaKind = "home" | "free" | "arrival" | "evisa" | "required" | "unknown";

export function visaFor(destCode: string): { kind: VisaKind; label: string } {
  const cc = countryCode(destCode);
  if (!cc) return { kind: "unknown", label: "" };
  if (cc === "AM") return { kind: "home", label: "" };
  const v = (places.visa[cc] ?? "").toLowerCase();
  if (!v) return { kind: "unknown", label: "" };
  if (/^\d+$/.test(v) || v === "visa free") return { kind: "free", label: "Առանց վիզայի" };
  if (v.includes("arrival")) return { kind: "arrival", label: "Վիզա տեղում" };
  if (v === "e-visa" || v === "eta") return { kind: "evisa", label: "Էլ. վիզա" };
  if (v.includes("no admission")) return { kind: "required", label: "Մուտքն արգելված է" };
  return { kind: "required", label: "Վիզա պետք է" };
}
